Update monitor

diff --git a/monitor b/monitor
--- a/monitor
+++ b/monitor
@@ -2,6 +2,25 @@
 
 set -e
 
+SMTPSRV=
+SMTPPORT=a
+SMTP_USERNAME=a
+MAIL_FROM=a
+SMTP_PASSWORD=a
+MAIL_BCC=a
+
+function sendemail(){
+    mail_subject="Your text"
+    mail_message_sign="
+Thank you,
+k8s"
+    mail_body="Hello All,
+        Node is not healthy.
+    if ! retry echo -e "${mail_body}\n${mail_message_sign}" | s-nail -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp="${SMTPSRV}:${SMTPPORT}" -S smtp-auth-user="${SMTP_USERNAME}" -S smtp-auth-password="${SMTP_PASSWORD}" -r "${MAIL_FROM}" -s "${mail_subject}" -b "${MAIL_BCC}" "${1}"; then
+        echo "***Failed***"
+    fi
+}
+
 command -v kubectl >/dev/null 2>&1 || { echo >&2 "I require kubectl but it's not installed.  Aborting."; exit 1; }
 
 nodes=$(kubectl get nodes | awk '{print $1}' | awk 'NR==2')
@@ -12,11 +31,11 @@ do
   result=$(kubectl top node "${line}")
   cpuper=$(echo $result | awk '{print $3}' | awk 'NR==2' | tr -d "%")
   if [[ "${cpuper}" -gt 70 ]]; then
-    echo "Trigger email"
+   sendemail abc@gmail.com
   fi
   memper=$(echo $result | awk '{print $5}' | awk 'NR==2' | tr -d "%")
   if [[ "${memper}" -gt 70 ]]; then
-    echo "Trigger email"
+    sendemail abc@gmail.com
   fi
 done <<< "$nodes"
 
